/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hildaproject;

/**
 *
 * @author David
 */
public class comptitle extends javax.swing.JFrame {

    /**
     * Creates new form comptitle
     */
    public comptitle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jComboBox6 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        a5 = new javax.swing.JComboBox();
        a4 = new javax.swing.JComboBox();
        a3 = new javax.swing.JComboBox();
        a2 = new javax.swing.JComboBox();
        a1 = new javax.swing.JComboBox();
        a6 = new javax.swing.JComboBox();
        a7 = new javax.swing.JComboBox();
        a8 = new javax.swing.JComboBox();
        a9 = new javax.swing.JComboBox();
        a10 = new javax.swing.JComboBox();
        a11 = new javax.swing.JComboBox();
        a12 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lab1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("1ST SEMESTER");

        jPanel1.setLayout(null);

        a5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F" }));
        jPanel1.add(a5);
        a5.setBounds(630, 270, 50, 26);

        a4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F" }));
        jPanel1.add(a4);
        a4.setBounds(630, 240, 50, 26);

        a3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F" }));
        jPanel1.add(a3);
        a3.setBounds(630, 210, 50, 26);

        a2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F" }));
        jPanel1.add(a2);
        a2.setBounds(630, 180, 50, 26);

        a1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F" }));
        jPanel1.add(a1);
        a1.setBounds(630, 150, 50, 26);

        a6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F" }));
        jPanel1.add(a6);
        a6.setBounds(630, 300, 50, 26);

        a7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F" }));
        jPanel1.add(a7);
        a7.setBounds(630, 330, 50, 26);

        a8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F" }));
        jPanel1.add(a8);
        a8.setBounds(630, 360, 50, 26);

        a9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F" }));
        jPanel1.add(a9);
        a9.setBounds(630, 390, 50, 26);

        a10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F" }));
        jPanel1.add(a10);
        a10.setBounds(630, 420, 50, 26);

        a11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F" }));
        jPanel1.add(a11);
        a11.setBounds(630, 450, 50, 26);

        a12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "A", "B", "C", "D", "E", "F" }));
        jPanel1.add(a12);
        a12.setBounds(630, 480, 50, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\David\\Documents\\NetBeansProjects\\hildaproject\\src\\hildaproject\\sub1.PNG")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 80, 730, 440);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setText("FIRST SEMESTER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 30, 320, 47);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel4.setText("GPA");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel3.setText("TOTAL CREDITS");

        jButton1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lab1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(lab1)
                .addGap(144, 144, 144)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lab1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lab1.setText("23");
        Object a;
        int A,B,C,D,E,F;
        A=5; B=4; C=3; D=2; E=1; F=0;
        a=a1.getSelectedItem();             
        a=a2.getSelectedItem();
        a=a3.getSelectedItem();
        a=a4.getSelectedItem();
        a=a5.getSelectedItem();
        a=a6.getSelectedItem();
        a=a7.getSelectedItem();
        a=a8.getSelectedItem();
        a=a9.getSelectedItem();
        a=a10.getSelectedItem();
        a=a11.getSelectedItem();
        a=a12.getSelectedItem();
        
        if(a.equals(A)){
            
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comptitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comptitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comptitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comptitle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comptitle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox a1;
    private javax.swing.JComboBox a10;
    private javax.swing.JComboBox a11;
    private javax.swing.JComboBox a12;
    private javax.swing.JComboBox a2;
    private javax.swing.JComboBox a3;
    private javax.swing.JComboBox a4;
    private javax.swing.JComboBox a5;
    private javax.swing.JComboBox a6;
    private javax.swing.JComboBox a7;
    private javax.swing.JComboBox a8;
    private javax.swing.JComboBox a9;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lab1;
    // End of variables declaration//GEN-END:variables
}
